### ISSUE TITLE
client.put method

### ISSUE THREAD

**Issue by davidkbainbridge** [Ubuntu-Solutions-Engineering/maasclient#10]
The MAAS API supports updates via the PUT request, but the client does not seem to have a put method.

**Comment by battlemidget** [comment]
Thanks, I'll try to make some time this week or next to see what needs to be done. One thing to note is the MAAS team is currently working on an official python 3 client that is intended to deprecate this one out. Their focus will be on making sure that everything this library supports is supported first in their client.

**Comment by battlemidget** [comment]
Fixed with https://github.com/Ubuntu-Solutions-Engineering/maasclient/commit/679a82903fa5be4f31fbd2f9065522d89b2084c6

Thanks!
